# Generated by Django 5.2.8 on 2026-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.TextField(blank=True),
        ),
    ]
