# Generated by Django 5.2.8 on 2026-02-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_remove_profile_categories_remove_profile_user_and_more'),
        ('portfolios', '0002_project_highlights_project_tools_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.designerprofile'),
        ),
    ]
