# Generated by Django 5.2.8 on 2026-02-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_remove_profile_categories_remove_profile_user_and_more'),
        ('portfolios', '0003_alter_project_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
