# Generated by Django 5.2.8 on 2026-02-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerprofile',
            name='availability_status',
            field=models.CharField(choices=[('Available Now', 'Available Now'), ('Unavailable Now', 'Unavailable Now')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_time', models.PositiveIntegerField(help_text='Delivery time in weeks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.designerprofile')),
            ],
        ),
    ]
